name: Sync upstream branches and tags
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *" # UTC


jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: FFmpeg/FFmpeg
          upstream_branch: master
          target_branch: master
          tags: true

